### ISSUE TITLE
As a PR, I have full access to my experiment so that I can carry out my research

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#13]

**Comment by Joshuapmb** [comment]
- [x] Code review is completed, and all changes incorporated.
- [x] Code is checked into the right branch in version control.
- [x] Code is fully integrated and built with no errors.
- [x] Code coverage tests were completed.
- [x] Code passed the regression test suite with no failures.
- [x] Code passed the acceptance criteria laid down by the customers.
