### ISSUE TITLE
As a CoR, I can access parts that the PR allows me to so that I can assist in the research

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#14]
- [x] Design new database structure
- [x] Implement database structure
- [x] Create page for assignation
- [x] Form to map a researcher to a project
- [x] Add creator of questionnaire to project when submitting / creating
- [x] Change data viewer and export to filter view by new table
- [x] Test and fix bugs

**Comment by Joshuapmb** [comment]
- [x] Code review is completed, and all changes incorporated.
- [x] Code is checked into the right branch in version control.
- [x] Code is fully integrated and built with no errors.
- [x] Code coverage tests were completed.
- [x] Code passed the regression test suite with no failures.
- [x] Code passed the acceptance criteria laid down by the customers.
