### ISSUE TITLE
As a lab manager, I can access all system functionality and information so I can continue my research at anytime

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#15]
- [x] View details
- [x] Edit my account details

**Comment by Joshuapmb** [comment]
- [x] Code review is completed, and all changes incorporated.
- [x] Code is checked into the right branch in version control.
- [x] Code is fully integrated and built with no errors.
- [x] Code coverage tests were completed.
- [x] Code passed the regression test suite with no failures.
- [x] Code passed the acceptance criteria laid down by the customers.
