### ISSUE TITLE
As a lab manager, I can manage users so I can modify their details when needed

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#16]
- [x] Change password functionality
- [x] Change username functionality
- [x] Change name of the user's account
- [x] Delete/undelete accounts

**Comment by Joshuapmb** [comment]
- [x] Code review is completed, and all changes incorporated.
- [x] Code is checked into the right branch in version control.
- [x] Code is fully integrated and built with no errors.
- [x] Code coverage tests were completed.
- [x] Code passed the regression test suite with no failures.
- [x] Code passed the acceptance criteria laid down by the customers.
