### ISSUE TITLE
As a researcher, I can create questions that are radio buttons to allow restriction in answers

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#2]

**Comment by Joshuapmb** [comment]
- [x]  Code review is completed, and all changes incorporated.
- [x]  Code is checked into the right branch in version control.
- [x]  Code is fully integrated and built with no errors.
- [x]  Code coverage tests were completed.
- [x]  Code passed the regression test suite with no failures.
- [x]  Code passed the acceptance criteria laid down by the customers.
