### ISSUE TITLE
As a participant, I am able to complete a questionnaire so that I can respond to a researcher

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#3]
- The design of the questionnaires should be easy to use
- The design of the questionnaires should be professional

- [x]  Respond to text questions
- [x] Respond to radio button questions

**Comment by Joshuapmb** [comment]
- [x] Code review is completed, and all changes incorporated.
- [x] Code is checked into the right branch in version control.
- [x] Code is fully integrated and built with no errors.
- [x] Code coverage tests were completed.
- [x] Code passed the regression test suite with no failures.
- [x] Code passed the acceptance criteria laid down by the customers.
