### ISSUE TITLE
As a researcher, I am able to export data so that I can analyse the questionnaire feedback

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#4]

**Comment by Joshuapmb** [comment]
- [x]  Code review is completed, and all changes incorporated.
- [x]  Code is checked into the right branch in version control.
- [x]  Code is fully integrated and built with no errors.
- [x]  Code coverage tests were completed.
- [x]  Code passed the regression test suite with no failures.
- [x]  Code passed the acceptance criteria laid down by the customers.
