### ISSUE TITLE
As the host, I can generate a transcript form so that I can analyse the data

### ISSUE THREAD

**Issue by JamesGit1** [JamesGit1/Team1Coursework#6]
The transcript must have high accuracy

**Comment by Joshuapmb** [comment]
- [x] Code review is completed, and all changes incorporated.
- [x] Code is checked into the right branch in version control.
- [x] Code is fully integrated and built with no errors.
- [x] Code coverage tests were completed.
- [x] Code passed the regression test suite with no failures.
- [x] Code passed the acceptance criteria laid down by the customers.
